### ISSUE TITLE
Recalculation bug

### ISSUE THREAD

**Issue by xReveres** [Iridium-Development/IridiumSkyblock#305]
**Describe the bug**
Every X seconds plugin automatically recalculates (asynchronously) island blocks and points.
I encountered 2 problems, look on attached films

**To Reproduce**

Problem 1:
1. Place some blocks
2. Open is top GUI
3. Wait and look on block count

Problem 2 (need any block limit upgrade):
1. Rich block limit
2. Hold right button (spam block place) and wait when iridium automatically recalculate blocks

**Expected behavior**
Keep good counted island blocks while recalculating

**Server Version and Plugin Version**
IridiumSkyblock: 3.0.6 (compiled from git)
Server version: Purpur 1.16.5

**Screenshots**
Problem 1: (Watch "Redstone: ..." position, and "Wartosc: ..." read as "Value: ...")
![bug](https://user-images.githubusercontent.com/8580908/126546746-d55d9a8d-9397-44ad-84a2-a961b1ad66d9.gif)

Problem 2:
https://user-images.githubusercontent.com/8580908/126547475-fe4033b4-27c8-4f2a-ac0d-9025dc2f34b0.mp4

**Comment by PeachesMLG** [comment]
Couldnt replicate issue 1 and 2, might be todo with The duplicates database entries? lmk if tomorrow's update fixes it

**Comment by PeachesMLG** [comment]
@xReveres has it been fixed?

**Comment by CayeOficial** [comment]
Waiting for Reveres reply cause I have this issue too

**Comment by xReveres** [comment]
@PeachesMLG sorry I was waiting for release on Github
Anyway problem with changing value is solved, but problem with resetting counted blocks still happen.
I think problem is in recalculation logic,
If plugin start recalculating it sets all counted blocks to 0, then plugin makes chunk snapshots and counting blocks asynchronously (this takes some time) and in this time when islands have 0 blocks (because they are not counted yet), players can place and bypass for example block limit upgrade or our custom upgrades.
Maybe you can't replicate this issue, because you have too good PC, we encountered this issue on server 2x2.2GHz CPU with 8Gb RAM

**Comment by PeachesMLG** [comment]
> @PeachesMLG sorry I was waiting for release on Github
> Anyway problem with changing value is solved, but problem with resetting counted blocks still happen.
> I think problem is in recalculation logic,
> If plugin start recalculating it sets all counted blocks to 0, then plugin makes chunk snapshots and counting blocks asynchronously (this takes some time) and in this time when islands have 0 blocks (because they are not counted yet), players can place and bypass for example block limit upgrade or our custom upgrades.
> Maybe you can't replicate this issue, because you have too good PC, we encountered this issue on server 2x2.2GHz CPU with 8Gb RAM

Sorry not sure I know what you mean can u send a video?

**Comment by xReveres** [comment]
I mean, yesterday row "Wartość" (ang. "Value" - island value) was the same, but today everything changes

https://user-images.githubusercontent.com/8580908/128087429-a892c551-eaab-4478-9841-0c8eae0b0c92.mp4

**Comment by CayeOficial** [comment]
I have another problem that's basically can be the same as this.

Island value changes randomly, there is no explanation or nothing to do, on my server there are people who have lost 1M of island level without any explanation for this bug

**Comment by MertUnverdi** [comment]
it was our database issue, should be fixed now, its fixed on 3.1.1?

**Comment by CayeOficial** [comment]
Idk, now I'm not using iridium Skyblock

**Comment by MertUnverdi** [comment]
I just asked to issue owner you can unsubrice issue ^^

**Comment by CayeOficial** [comment]
Sorry

**Comment by xReveres** [comment]
@MertUnverdi no, problem still exists. 
In my opinion the problem is not in database but in asynchronous recalculation

**Comment by CayeOficial** [comment]
I have the fix for this issue, do you want to see it?

**Comment by MertUnverdi** [comment]
@CayeOficial You will say "using another plugin"?..
So yes, why being a stupid ?

**Comment by CayeOficial** [comment]
Switch to Superior Skyblock 👌

**Comment by xReveres** [comment]
@MertUnverdi yes, values are updated after recalculation, but before all values are reset to 0
https://github.com/Iridium-Development/IridiumSkyblock/blob/566e3f22a1bad17217d546d83fbcee66da8d9c2d/src/main/java/com/iridium/iridiumskyblock/managers/IslandManager.java#L827

**Comment by MertUnverdi** [comment]
Oh sorry i didn't checkec this before i'll fix it when i at home ty

**Comment by PeachesMLG** [comment]
Two completly seperate issues
