### ISSUE TITLE
Movement Bug/Glitch on Latest Version 4.0.9.1 for Bedrock clients

### ISSUE THREAD

**Issue by TomcatHD** [Iridium-Development/IridiumSkyblock#871]
**Describe the bug**
players movement on bedrock client is extremely laggy/position constantly gets resetted, blocks that have been broken re- appear, jumping around a lot eventually gets the player unable to move at all.
**To Reproduce**
1. Go to your island
2. Jump around
3. break blocks
4. move around 

**Expected behavior**
normal minecraft movement

**Server and Plugin Version**
Server on Paper 1.20.1, IridiumSkyblock on 4.0.9.1

**Screenshots**

**Logs**
the basic "[player ]moved too quickly" movement error

**Additional context**
i have tested removing all plugins on my server (except vault) but the issue was still persistent, however downgrading and testing older versions of IridiumSkyblock everything worked perfectly fine.

**Comment by sh0inx** [comment]
any particular reason we closed this issue?

**Comment by TomcatHD** [comment]
seems like it was just an old config that was causing this issue, however no errors in log

**Comment by sh0inx** [comment]
gotcha; i did some optimization of the playerMoveEventListener, so this may be better resolved in a future update - can you tell us what settings you had enabled that caused the lag?

**Comment by TomcatHD** [comment]
i cant tell, i just let it regenerate all the files.

**Comment by sh0inx** [comment]
no worries! if you ever figure it out, feel free to update this issue with that information, but it's not pressing

**Comment by TomcatHD** [comment]
will do!

**Comment by TomcatHD** [comment]
seems like i still get the same error/movement glitch on the latest version even with a freshly generated config and world after a few server restarts, weird. no errors in console. i hate bedrock.

**Comment by TomcatHD** [comment]
@sh0inx could you confirm this issue please, or is this plugin simply not supporting bedrock at all? its happening after about 3-4 server restarts for some odd reason.

**Comment by sh0inx** [comment]
its an issue that i can replicate, but i can't tell you why it happens - because this is an issue that only happens for bedrock players, its not a priority to fix
however, if we can narrow down the cause and it is fixable on our end, i want to address it

**Comment by sh0inx** [comment]
this plugin does not support geyser/bedrock clients, as it is entirely unpredictable, and there are some issues that we simply cannot fix

**Comment by sh0inx** [comment]
you can try using the beta release in the discord, as it has an update to the player event movement listener that might help with this, but im out of ideas if that doesnt work for you

**Comment by TomcatHD** [comment]
> you can try using the beta release in the discord, as it has an update to the player event movement listener that might help with this, but im out of ideas if that doesnt work for you

thanks for the reply, i have tried using the beta on bedrock/geyser and im now getting the following error message, hopefully this helps:

![Unbenannt](https://github.com/Iridium-Development/IridiumSkyblock/assets/142759713/e393f212-d572-455b-8619-104e8c2dfcdf)

**Comment by sh0inx** [comment]
use the pinned version in the beta channel on our discord

**Comment by TomcatHD** [comment]
> use the pinned version in the beta channel on our discord

thats the one ive used, V 4.1.0 Beta 3 correct?

**Comment by sh0inx** [comment]
![image](https://github.com/Iridium-Development/IridiumSkyblock/assets/24255866/072bb483-0e29-49ed-acb3-9e97bae0a75a)

**Comment by TomcatHD** [comment]
> ![image](https://private-user-images.githubusercontent.com/24255866/344359732-072bb483-0e29-49ed-acb3-9e97bae0a75a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MjY5MDIsIm5iZiI6MTcxOTYyNjYwMiwicGF0aCI6Ii8yNDI1NTg2Ni8zNDQzNTk3MzItMDcyYmI0ODMtMGUyOS00OWVkLWFjYjMtOWU5N2JhZTBhNzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDAyMDMyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1N2I3NjM3MTU4MzM5Mjk2ZjgwYWExMGZmODJmYTkwMzQ3ZjNjMjNiYjdhOWUzZGQ1OWNlMmM0MmQ4MmMwYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nHtGsl7AGiOA0JtZAPK1_akcq63Rznqul-DbQwwvFJc)

found it, thanks! the error message is now gone but the movement bugg still exists :/ ill have to use a different skyblock plugin then, really appreciate the help though and wishing you guys good luck on further developement on this Plugin :) its definetely the best Java Skyblock Plugin out there <3
